### ISSUE TITLE
Unstable navigation bar for guest drop down menu mobile view

### ISSUE THREAD

**Issue by blockbuster15** [gscdit/betterpledge-frontend#16]
# Describe the bug
There is a problem in navigation bar when open in small devices.

# To Reproduce
1. open the page in the small-screen device

# Expected behavior
1. the drop-down navigation bar should be stable across all mobile devices.

#Screenshot in small screen devices
![image](https://user-images.githubusercontent.com/37174789/50903752-9dd7ad80-1444-11e9-8833-84768b326d86.png)

**Comment by preetmishra** [comment]
Fixed in #18
