### ISSUE TITLE
CORS Request Blocked

### ISSUE THREAD

**Issue by naseemali925** [gscdit/betterpledge-frontend#17]
## Describe the bug
Unable to register due to CORS policy

## To reproduce
Try registering from dev server

## Expected behavior
User should be able to register properly

## Screenshot
![screenshot 12](https://user-images.githubusercontent.com/6770106/50907922-8c939e80-144e-11e9-9f84-4f5166a729f9.png)

**Comment by makkoncept** [comment]
done!
