### ISSUE TITLE
Fix Horizontal Scroll

### ISSUE THREAD

**Issue by NaveenShivnani** [gscdit/betterpledge-frontend#19]
Fix the issue of horizontal scrolling on login landing page.
![screenshot 34](https://user-images.githubusercontent.com/26898615/50918754-1b141a00-1467-11e9-8ba7-93c718a7039a.png)

**Comment by preetmishra** [comment]
Fixed the issue in a0aa47fc390a985b45260977444d75ce47b1e66b

**Comment by preetmishra** [comment]
Fixed the issue in a0aa47fc390a985b45260977444d75ce47b1e66b
