### ISSUE TITLE
Items value in cart can go in negative

### ISSUE THREAD

**Issue by LokeshKarki** [gscdit/betterpledge-frontend#3]
error steps- 
1. go to cart
2. continue shopping
3. click on the - button and click checkout
4. hence the bug

what to improve:  - disable the - button unless we press the + one

**Comment by ashishprasad12** [comment]
Can you please add a screenshot of the issue?

**Comment by LokeshKarki** [comment]
![de](https://user-images.githubusercontent.com/33099008/50835370-89c87900-137c-11e9-8e28-21ee69b205f9.png)
