### ISSUE TITLE
Less size allocation in name bar

### ISSUE THREAD

**Issue by LokeshKarki** [gscdit/betterpledge-frontend#5]
things to fix - when we register our self, in the name space/size allocation is very less, increase varchar size. And giving spaces while typing full name says "Please enter valid name", fix that.

**Comment by iamshouvikmitra** [comment]
@makkoncept should be able to make appropriate feilds in database for supporting first and last name separately.

**Comment by makkoncept** [comment]
@iamshouvikmitra I have done this locally. Tell me when to push the update, as the database will reset and thus we will have to create users again.

**Comment by iamshouvikmitra** [comment]
Go ahead no issue. It's green🚦from my side. @VipulChikara will re-build and publish to dev server. I will add the products.
