### ISSUE TITLE
Cards in Problems area are stretched!

### ISSUE THREAD

**Issue by iamshouvikmitra** [gscdit/betterpledge-frontend#75]
![image](https://user-images.githubusercontent.com/24479402/57179309-2f5aa780-6e9a-11e9-8dce-24b21a0aca73.png)

**Comment by sanyam99ag** [comment]
![IMG-20190505-WA0007](https://user-images.githubusercontent.com/39384430/57194903-043f8900-6f6a-11e9-86ac-fa3a130c0f38.jpg)
